package xdb

const (
	TableXAdminLoginLog = "x_admin_login_log"
	TableXAdminOptLog   = "x_admin_opt_log"
	TableXAdminRole     = "x_admin_role"
	TableXAdminUser     = "x_admin_user"
	TableXChat          = "x_chat"
	TableXChatBanIp     = "x_chat_ban_ip"
	TableXHongbao       = "x_hongbao"
	TableXHostSeller    = "x_host_seller"
	TableXKv            = "x_kv"
	TableXLiveProvider  = "x_live_provider"
	TableXLiveRoom      = "x_live_room"
	TableXSeller        = "x_seller"
	TableXUser          = "x_user"
)

const (
	LoginIp         = "login_ip"
	K               = "k"
	PullUrl         = "pull_url"
	Name            = "name"
	Title           = "title"
	LoginIpLocation = "login_ip_location"
	Memo            = "memo"
	SellerId        = "seller_id"
	ReqData         = "req_data"
	Ip              = "ip"
	Content         = "content"
	PullKey         = "pull_key"
	SellerName      = "seller_name"
	ReqIpLocation   = "req_ip_location"
	Parent          = "parent"
	LoginGoogle     = "login_google"
	Password        = "password"
	RoomId          = "room_id"
	ChatState       = "chat_state"
	TotalAmount     = "total_amount"
	PushUrl         = "push_url"
	Id              = "id"
	State           = "state"
	Agent           = "agent"
	OptGoogle       = "opt_google"
	Sender          = "sender"
	Account         = "account"
	Token           = "token"
	Host            = "host"
	Provider        = "provider"
	LiveUrl         = "live_url"
	ReqIp           = "req_ip"
	RoleName        = "role_name"
	LoginCount      = "login_count"
	UsedAmount      = "used_amount"
	IsVisitor       = "is_visitor"
	V               = "v"
	CreateTime      = "create_time"
	OptName         = "opt_name"
	RoleData        = "role_data"
	LoginTime       = "login_time"
	AdminAccount    = "admin_account"
	ReqPath         = "req_path"
	IpLocation      = "ip_location"
	TotalCount      = "total_count"
	UsedCount       = "used_count"
	PushKey         = "push_key"
)
