package xdb

const (
	StateYes = 1 // 启用
	StateNo  = 2 // 禁用
)
const (
	RoleData        = "role_data"
	UsedCount       = "used_count"
	PushUrl         = "push_url"
	LoginIp         = "login_ip"
	Parent          = "parent"
	Id              = "id"
	V               = "v"
	Agent           = "agent"
	OptName         = "opt_name"
	ReqData         = "req_data"
	LiveUrl         = "live_url"
	ChatState       = "chat_state"
	IsVisitor       = "is_visitor"
	SellerId        = "seller_id"
	LoginTime       = "login_time"
	UserId          = "user_id"
	UsedAmount      = "used_amount"
	RoleName        = "role_name"
	LoginGoogle     = "login_google"
	RoomId          = "room_id"
	Sender          = "sender"
	CreateTime      = "create_time"
	TotalAmount     = "total_amount"
	PullUrl         = "pull_url"
	ReqPath         = "req_path"
	TotalCount      = "total_count"
	LoginIpLocation = "login_ip_location"
	Memo            = "memo"
	ReqIpLocation   = "req_ip_location"
	K               = "k"
	SellerName      = "seller_name"
	Account         = "account"
	OptGoogle       = "opt_google"
	Password        = "password"
	Name            = "name"
	Token           = "token"
	ReqIp           = "req_ip"
	IpLocation      = "ip_location"
	Host            = "host"
	PushKey         = "push_key"
	State           = "state"
	LoginCount      = "login_count"
	Ip              = "ip"
	PullKey         = "pull_key"
	AdminAccount    = "admin_account"
	Content         = "content"
	LoginLocation   = "login_location"
	Provider        = "provider"
	Title           = "title"
)
