// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameXAdminOptLog = "x_admin_opt_log"

// XAdminOptLog mapped from table <x_admin_opt_log>
type XAdminOptLog struct {
	ID            int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:自增Id" json:"id"`               // 自增Id
	SellerID      int32     `gorm:"column:seller_id;comment:运营商" json:"seller_id"`                                // 运营商
	Account       string    `gorm:"column:account;comment:账号" json:"account"`                                     // 账号
	OptName       string    `gorm:"column:opt_name;comment:操作名称" json:"opt_name"`                                 // 操作名称
	ReqPath       string    `gorm:"column:req_path;comment:请求路径" json:"req_path"`                                 // 请求路径
	ReqData       string    `gorm:"column:req_data;comment:请求参数" json:"req_data"`                                 // 请求参数
	ReqIP         string    `gorm:"column:req_ip;comment:请求Ip" json:"req_ip"`                                     // 请求Ip
	ReqIPLocation string    `gorm:"column:req_ip_location;comment:请求Ip所在地区" json:"req_ip_location"`               // 请求Ip所在地区
	CreateTime    time.Time `gorm:"column:create_time;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"` // 创建时间
}

// TableName XAdminOptLog's table name
func (*XAdminOptLog) TableName() string {
	return TableNameXAdminOptLog
}
