// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameXAdminLoginLog = "x_admin_login_log"

// XAdminLoginLog mapped from table <x_admin_login_log>
type XAdminLoginLog struct {
	ID              int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:自增Id" json:"id"`               // 自增Id
	SellerID        int32     `gorm:"column:seller_id;comment:运营商" json:"seller_id"`                                // 运营商
	Account         string    `gorm:"column:account;comment:账号" json:"account"`                                     // 账号
	Token           string    `gorm:"column:token;comment:登录的token" json:"token"`                                   // 登录的token
	LoginIP         string    `gorm:"column:login_ip;comment:登录Ip" json:"login_ip"`                                 // 登录Ip
	LoginIPLocation string    `gorm:"column:login_ip_location;comment:登录ip所在地区" json:"login_ip_location"`           // 登录ip所在地区
	Memo            string    `gorm:"column:memo;comment:备注" json:"memo"`                                           // 备注
	CreateTime      time.Time `gorm:"column:create_time;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"` // 创建时间
}

// TableName XAdminLoginLog's table name
func (*XAdminLoginLog) TableName() string {
	return TableNameXAdminLoginLog
}
