// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameXLiveRoom = "x_live_room"

// XLiveRoom mapped from table <x_live_room>
type XLiveRoom struct {
	ID         int32     `gorm:"column:id;primaryKey;autoIncrement:true;comment:id" json:"id"`                 // id
	SellerID   int32     `gorm:"column:seller_id;comment:运营商" json:"seller_id"`                                // 运营商
	Name       string    `gorm:"column:name;comment:直播间名称" json:"name"`                                        // 直播间名称
	Account    string    `gorm:"column:account;comment:主播账号" json:"account"`                                   // 主播账号
	Title      string    `gorm:"column:title;comment:直播间标题" json:"title"`                                      // 直播间标题
	PushURL    string    `gorm:"column:push_url;comment:推流地址" json:"push_url"`                                 // 推流地址
	PullURL    string    `gorm:"column:pull_url;comment:拉流地址" json:"pull_url"`                                 // 拉流地址
	LiveURL    string    `gorm:"column:live_url;comment:前端地址" json:"live_url"`                                 // 前端地址
	State      int32     `gorm:"column:state;not null;comment:状态1正在直播,2未在直播" json:"state"`                     // 状态1正在直播,2未在直播
	CreateTime time.Time `gorm:"column:create_time;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"` // 创建时间
}

// TableName XLiveRoom's table name
func (*XLiveRoom) TableName() string {
	return TableNameXLiveRoom
}
