// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin_log/get_login_log": {
            "get": {
                "tags": [
                    "后台日志"
                ],
                "summary": "获取登录日志",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "x-token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "操作人",
                        "name": "account",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "渠道商",
                        "name": "channel_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "结束时间",
                        "name": "end_time",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "登录Ip",
                        "name": "login_ip",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页数量",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "运营商",
                        "name": "seller_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "开始时间",
                        "name": "start_time",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.XAdminLoginLog"
                            }
                        }
                    }
                }
            }
        },
        "/admin_log/get_opt_log": {
            "get": {
                "tags": [
                    "后台日志"
                ],
                "summary": "获取操作日志",
                "parameters": [
                    {
                        "type": "string",
                        "description": "操作人",
                        "name": "account",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "渠道商",
                        "name": "channel_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "结束时间",
                        "name": "end_time",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "操作名",
                        "name": "opt_name",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页数量",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "运营商",
                        "name": "seller_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "开始时间",
                        "name": "start_time",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.XAdminOptLog"
                            }
                        }
                    }
                }
            }
        },
        "/admin_role/create_admin_role": {
            "post": {
                "tags": [
                    "后台角色"
                ],
                "summary": "新增角色",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "x-token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "验证码",
                        "name": "VerifyCode",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "body参数",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service_admin.CreateAdminRoleReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功"
                    }
                }
            }
        },
        "/admin_role/delete_admin_role": {
            "delete": {
                "tags": [
                    "后台角色"
                ],
                "summary": "删除角色",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "x-token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "验证码",
                        "name": "VerifyCode",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "body参数",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service_admin.DeleteAdminRoleReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功"
                    }
                }
            }
        },
        "/admin_role/get_admin_role": {
            "get": {
                "tags": [
                    "后台角色"
                ],
                "summary": "获取角色列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "x-token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页数量",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "角色名",
                        "name": "role_name",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "运营商",
                        "name": "seller_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.XAdminRole"
                            }
                        }
                    }
                }
            }
        },
        "/admin_role/update_admin_role": {
            "patch": {
                "tags": [
                    "后台角色"
                ],
                "summary": "更新角色",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "x-token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "验证码",
                        "name": "VerifyCode",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "body参数",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service_admin.UpdateAdminRoleReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功"
                    }
                }
            }
        },
        "/admin_user/create_admin_user": {
            "post": {
                "tags": [
                    "后台用户"
                ],
                "summary": "新增管理员账号",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "x-token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "验证码",
                        "name": "VerifyCode",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "body参数",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service_admin.CreateAdminUserReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功"
                    }
                }
            }
        },
        "/admin_user/delete_admin_user": {
            "delete": {
                "tags": [
                    "后台用户"
                ],
                "summary": "删除管理员账号",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "x-token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "验证码",
                        "name": "VerifyCode",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "body参数",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service_admin.DeleteAdminUserReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功"
                    }
                }
            }
        },
        "/admin_user/get_admin_user": {
            "get": {
                "tags": [
                    "后台用户"
                ],
                "summary": "获取管理员列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "x-token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "账号",
                        "name": "account",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页数量",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "运营商",
                        "name": "seller_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.XAdminUser"
                            }
                        }
                    }
                }
            }
        },
        "/admin_user/set_login_googlesecret": {
            "post": {
                "tags": [
                    "后台用户"
                ],
                "summary": "设置登录验证码",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "x-token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "验证码",
                        "name": "VerifyCode",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "body参数",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service_admin.SetLoginGoogleReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/service_admin.SetLoginGoogleRes"
                        }
                    }
                }
            }
        },
        "/admin_user/set_opt_googlesecret": {
            "post": {
                "tags": [
                    "后台用户"
                ],
                "summary": "设置操作验证码",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "x-token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "验证码",
                        "name": "VerifyCode",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "body参数",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service_admin.SetOptGoogleReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/service_admin.SetOptGoogleRes"
                        }
                    }
                }
            }
        },
        "/admin_user/update_admin_user": {
            "patch": {
                "tags": [
                    "后台用户"
                ],
                "summary": "更新管理员账号",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "x-token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "验证码",
                        "name": "VerifyCode",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "body参数",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service_admin.UpdateAdminUserReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功"
                    }
                }
            }
        },
        "/admin_user/user_login": {
            "post": {
                "tags": [
                    "后台登录"
                ],
                "summary": "管理员登录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "验证码",
                        "name": "VerifyCode",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "body参数",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service_admin.AdminUserLoginReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/service_admin.AdminUserLoginRes"
                        }
                    }
                }
            }
        },
        "/admin_user/user_logout": {
            "post": {
                "tags": [
                    "后台登录"
                ],
                "summary": "管理员退出",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "x-token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功"
                    }
                }
            }
        },
        "/config/get_config": {
            "post": {
                "tags": [
                    "系统设置"
                ],
                "summary": "获取配置",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "x-token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "筛选参数",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/service_admin.GetXConfigReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/service_admin.GetXConfigRes"
                        }
                    }
                }
            }
        },
        "/config/update_config": {
            "patch": {
                "tags": [
                    "系统设置"
                ],
                "summary": "更新配置",
                "parameters": [
                    {
                        "description": "筛选参数",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/service_admin.GetXConfigReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功"
                    }
                }
            }
        },
        "/seller/create_seller": {
            "post": {
                "tags": [
                    "运营商"
                ],
                "summary": "新增运营商",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "x-token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "验证码",
                        "name": "VerifyCode",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "body参数",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service_admin.CreateXSellerReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功"
                    }
                }
            }
        },
        "/seller/delete_seller": {
            "delete": {
                "tags": [
                    "运营商"
                ],
                "summary": "删除运营商",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "x-token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "验证码",
                        "name": "VerifyCode",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "body参数",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service_admin.DeleteXSellerReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功"
                    }
                }
            }
        },
        "/seller/get_seller": {
            "get": {
                "tags": [
                    "运营商"
                ],
                "summary": "获取运营商列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "x-token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页数量",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "运营商",
                        "name": "seller_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "运营商名称",
                        "name": "seller_name",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.XSeller"
                            }
                        }
                    }
                }
            }
        },
        "/seller/update_seller": {
            "patch": {
                "tags": [
                    "运营商"
                ],
                "summary": "更新运营商",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "x-token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "验证码",
                        "name": "VerifyCode",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "body参数",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service_admin.UpdateXSellerReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功"
                    }
                }
            }
        }
    },
    "definitions": {
        "model.XAdminLoginLog": {
            "type": "object",
            "properties": {
                "account": {
                    "description": "账号",
                    "type": "string"
                },
                "create_time": {
                    "description": "创建时间",
                    "type": "string"
                },
                "id": {
                    "description": "自增Id",
                    "type": "integer"
                },
                "ip_location": {
                    "description": "ip地理位置",
                    "type": "string"
                },
                "login_ip": {
                    "description": "最近一次登录Ip",
                    "type": "string"
                },
                "memo": {
                    "description": "备注",
                    "type": "string"
                },
                "seller_id": {
                    "description": "运营商",
                    "type": "integer"
                }
            }
        },
        "model.XAdminOptLog": {
            "type": "object",
            "properties": {
                "account": {
                    "description": "账号",
                    "type": "string"
                },
                "create_time": {
                    "description": "创建时间",
                    "type": "string"
                },
                "id": {
                    "description": "自增Id",
                    "type": "integer"
                },
                "ip_location": {
                    "description": "Ip地理位置",
                    "type": "string"
                },
                "opt_name": {
                    "description": "请求路径",
                    "type": "string"
                },
                "req_data": {
                    "description": "请求参数",
                    "type": "string"
                },
                "req_ip": {
                    "description": "请求的Ip",
                    "type": "string"
                },
                "req_path": {
                    "description": "请求路径",
                    "type": "string"
                },
                "seller_id": {
                    "description": "运营商",
                    "type": "integer"
                }
            }
        },
        "model.XAdminRole": {
            "type": "object",
            "properties": {
                "create_time": {
                    "description": "创建时间",
                    "type": "string"
                },
                "id": {
                    "description": "自增Id",
                    "type": "integer"
                },
                "memo": {
                    "description": "备注",
                    "type": "string"
                },
                "parent": {
                    "description": "上级角色",
                    "type": "string"
                },
                "role_data": {
                    "description": "权限数据",
                    "type": "string"
                },
                "role_name": {
                    "description": "角色名",
                    "type": "string"
                },
                "seller_id": {
                    "description": "运营商",
                    "type": "integer"
                },
                "state": {
                    "description": "状态 1开启,2关闭",
                    "type": "integer"
                }
            }
        },
        "model.XAdminUser": {
            "type": "object",
            "properties": {
                "account": {
                    "description": "账号",
                    "type": "string"
                },
                "create_time": {
                    "description": "创建时间",
                    "type": "string"
                },
                "id": {
                    "description": "自增Id",
                    "type": "integer"
                },
                "login_count": {
                    "description": "登录次数",
                    "type": "integer"
                },
                "login_ip": {
                    "description": "最后登录Ip",
                    "type": "string"
                },
                "login_time": {
                    "description": "最后登录时间",
                    "type": "string"
                },
                "memo": {
                    "description": "备注",
                    "type": "string"
                },
                "role_name": {
                    "description": "角色",
                    "type": "string"
                },
                "seller_id": {
                    "description": "运营商",
                    "type": "integer"
                },
                "state": {
                    "description": "状态 1开启,2关闭",
                    "type": "integer"
                }
            }
        },
        "model.XConfig": {
            "type": "object",
            "properties": {
                "config_name": {
                    "description": "配置名称",
                    "type": "string"
                },
                "config_value": {
                    "description": "配置值",
                    "type": "string"
                },
                "create_time": {
                    "description": "创建时间",
                    "type": "string"
                },
                "id": {
                    "description": "配置Id",
                    "type": "integer"
                },
                "memo": {
                    "description": "备注",
                    "type": "string"
                },
                "seller_id": {
                    "description": "运营商Id",
                    "type": "integer"
                }
            }
        },
        "model.XSeller": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "自增Id",
                    "type": "integer"
                },
                "memo": {
                    "description": "备注",
                    "type": "string"
                },
                "seller_id": {
                    "description": "运营商",
                    "type": "integer"
                },
                "seller_name": {
                    "description": "运营商名称",
                    "type": "string"
                },
                "state": {
                    "description": "状态 1开启 2关闭",
                    "type": "integer"
                }
            }
        },
        "service_admin.AdminUserLoginReq": {
            "type": "object",
            "required": [
                "account",
                "password"
            ],
            "properties": {
                "account": {
                    "description": "账号",
                    "type": "string"
                },
                "password": {
                    "description": "密码",
                    "type": "string"
                }
            }
        },
        "service_admin.AdminUserLoginRes": {
            "type": "object",
            "properties": {
                "account": {
                    "description": "账号",
                    "type": "string"
                },
                "auth_data": {
                    "description": "权限数据",
                    "type": "string"
                },
                "login_count": {
                    "description": "登录次数",
                    "type": "integer"
                },
                "login_ip": {
                    "description": "登录Ip",
                    "type": "string"
                },
                "login_time": {
                    "description": "登录时间",
                    "type": "string"
                },
                "seller_id": {
                    "description": "运营商",
                    "type": "integer"
                },
                "token": {
                    "description": "token",
                    "type": "string"
                },
                "utc_offset": {
                    "description": "当地时区与utc的偏移量",
                    "type": "integer"
                }
            }
        },
        "service_admin.CreateAdminRoleReq": {
            "type": "object",
            "required": [
                "parent",
                "role_data",
                "role_name",
                "seller_id",
                "state"
            ],
            "properties": {
                "memo": {
                    "description": "备注",
                    "type": "string"
                },
                "parent": {
                    "description": "上级角色",
                    "type": "string"
                },
                "role_data": {
                    "description": "权限数据",
                    "type": "string"
                },
                "role_name": {
                    "description": "角色",
                    "type": "string"
                },
                "seller_id": {
                    "description": "运营商",
                    "type": "integer"
                },
                "state": {
                    "description": "状态 1开启,2关闭",
                    "type": "integer"
                }
            }
        },
        "service_admin.CreateAdminUserReq": {
            "type": "object",
            "required": [
                "account",
                "password",
                "role_name",
                "seller_id",
                "state"
            ],
            "properties": {
                "account": {
                    "description": "账号",
                    "type": "string"
                },
                "memo": {
                    "description": "备注",
                    "type": "string"
                },
                "password": {
                    "description": "登录密码",
                    "type": "string"
                },
                "role_name": {
                    "description": "角色",
                    "type": "string"
                },
                "seller_id": {
                    "description": "运营商",
                    "type": "integer"
                },
                "state": {
                    "description": "状态 1开启,2关闭",
                    "type": "integer"
                }
            }
        },
        "service_admin.CreateXSellerReq": {
            "type": "object",
            "required": [
                "seller_id",
                "seller_name",
                "state"
            ],
            "properties": {
                "memo": {
                    "description": "备注",
                    "type": "string"
                },
                "seller_id": {
                    "description": "运营商",
                    "type": "integer"
                },
                "seller_name": {
                    "description": "运营商名称",
                    "type": "string"
                },
                "state": {
                    "description": "状态 1开启,2关闭",
                    "type": "integer"
                }
            }
        },
        "service_admin.DeleteAdminRoleReq": {
            "type": "object",
            "required": [
                "role_name",
                "seller_id"
            ],
            "properties": {
                "role_name": {
                    "description": "角色",
                    "type": "string"
                },
                "seller_id": {
                    "description": "运营商",
                    "type": "integer"
                }
            }
        },
        "service_admin.DeleteAdminUserReq": {
            "type": "object",
            "required": [
                "account",
                "seller_id"
            ],
            "properties": {
                "account": {
                    "description": "账号",
                    "type": "string"
                },
                "seller_id": {
                    "description": "运营商",
                    "type": "integer"
                }
            }
        },
        "service_admin.DeleteXSellerReq": {
            "type": "object",
            "required": [
                "seller_id"
            ],
            "properties": {
                "seller_id": {
                    "description": "运营商",
                    "type": "integer"
                }
            }
        },
        "service_admin.GetXConfigReq": {
            "type": "object",
            "required": [
                "seller_id"
            ],
            "properties": {
                "channel_id": {
                    "description": "渠道商",
                    "type": "integer"
                },
                "config_name": {
                    "description": "配置名称",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "seller_id": {
                    "description": "运营商",
                    "type": "integer"
                }
            }
        },
        "service_admin.GetXConfigRes": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.XConfig"
                    }
                }
            }
        },
        "service_admin.SetLoginGoogleReq": {
            "type": "object",
            "required": [
                "account",
                "seller_id"
            ],
            "properties": {
                "account": {
                    "description": "账号",
                    "type": "string"
                },
                "seller_id": {
                    "description": "运营商",
                    "type": "integer"
                }
            }
        },
        "service_admin.SetLoginGoogleRes": {
            "type": "object",
            "properties": {
                "google_secret": {
                    "description": "登录验证码",
                    "type": "string"
                }
            }
        },
        "service_admin.SetOptGoogleReq": {
            "type": "object",
            "required": [
                "account",
                "seller_id"
            ],
            "properties": {
                "account": {
                    "description": "账号",
                    "type": "string"
                },
                "seller_id": {
                    "description": "运营商",
                    "type": "integer"
                }
            }
        },
        "service_admin.SetOptGoogleRes": {
            "type": "object",
            "properties": {
                "google_secret": {
                    "description": "操作验证码",
                    "type": "string"
                }
            }
        },
        "service_admin.UpdateAdminRoleReq": {
            "type": "object",
            "required": [
                "role_name",
                "seller_id"
            ],
            "properties": {
                "memo": {
                    "description": "备注",
                    "type": "string"
                },
                "parent": {
                    "description": "上级角色",
                    "type": "string"
                },
                "role_data": {
                    "description": "权限数据",
                    "type": "string"
                },
                "role_name": {
                    "description": "角色",
                    "type": "string"
                },
                "seller_id": {
                    "description": "运营商",
                    "type": "integer"
                },
                "state": {
                    "description": "状态 1开启,2关闭",
                    "type": "integer"
                }
            }
        },
        "service_admin.UpdateAdminUserReq": {
            "type": "object",
            "required": [
                "account",
                "seller_id"
            ],
            "properties": {
                "account": {
                    "description": "账号",
                    "type": "string"
                },
                "memo": {
                    "description": "备注",
                    "type": "string"
                },
                "password": {
                    "description": "登录密码",
                    "type": "string"
                },
                "role_name": {
                    "description": "角色",
                    "type": "string"
                },
                "seller_id": {
                    "description": "运营商",
                    "type": "integer"
                },
                "state": {
                    "description": "状态 1开启,2关闭",
                    "type": "integer"
                }
            }
        },
        "service_admin.UpdateXSellerReq": {
            "type": "object",
            "required": [
                "seller_id"
            ],
            "properties": {
                "memo": {
                    "description": "备注",
                    "type": "string"
                },
                "seller_id": {
                    "description": "运营商",
                    "type": "integer"
                },
                "seller_name": {
                    "description": "运营商名称",
                    "type": "string"
                },
                "state": {
                    "description": "状态 1开启,2关闭",
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "": {
            "type": "apiKey",
            "name": "x-token",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "adminapi",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
