basePath: /api/v1
definitions:
  service_user.UserLoginReq:
    properties:
      account:
        description: 账号
        type: string
      is_visitor:
        description: 是否游客
        type: integer
      password:
        description: 密码
        type: string
      sales_id:
        description: 业务员
        type: integer
    required:
    - account
    type: object
  service_user.UserLoginRes:
    properties:
      account:
        description: 账号
        type: string
      is_visitor:
        description: 是否游客
        type: integer
      live_data:
        description: 直播数据
        type: string
      token:
        description: token
        type: string
      user_id:
        description: 用户Id
        type: integer
    type: object
info:
  contact: {}
  title: xclientapi
  version: "1.0"
paths:
  /user/user_login:
    post:
      parameters:
      - description: body参数
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/service_user.UserLoginReq'
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/service_user.UserLoginRes'
      summary: 玩家登录
      tags:
      - 玩家
securityDefinitions:
  "":
    in: header
    name: x-token
    type: apiKey
swagger: "2.0"
