basePath: /api/v1
definitions:
  service_app.AppGetLiveInfoReq:
    properties:
      user_id:
        type: integer
    type: object
  service_app.AppGetLiveInfoRes:
    properties:
      user_id:
        type: integer
    type: object
  service_user.UserLoginReq:
    properties:
      account:
        type: string
      is_visitor:
        type: integer
      password:
        type: string
    required:
    - account
    type: object
  service_user.UserLoginRes:
    properties:
      account:
        type: string
      is_visitor:
        type: integer
      token:
        type: string
      user_id:
        type: integer
    type: object
info:
  contact: {}
  title: xclientapi
  version: "1.0"
paths:
  /app/get_live_info:
    get:
      parameters:
      - description: token
        in: header
        name: x-token
        required: true
        type: string
      - description: 筛选参数
        in: body
        name: body
        schema:
          $ref: '#/definitions/service_app.AppGetLiveInfoReq'
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/service_app.AppGetLiveInfoRes'
      summary: 获取直播信息
      tags:
      - 应用
  /user/user_login:
    post:
      parameters:
      - description: body参数
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/service_user.UserLoginReq'
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/service_user.UserLoginRes'
      summary: 玩家登录
      tags:
      - 玩家
securityDefinitions:
  "":
    in: header
    name: x-token
    type: apiKey
swagger: "2.0"
