// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameXAdminRole = "x_admin_role"

// XAdminRole mapped from table <x_admin_role>
type XAdminRole struct {
	ID         int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:自增Id" json:"id"`               // 自增Id
	SellerID   int32     `gorm:"column:seller_id;comment:运营商" json:"seller_id"`                                // 运营商
	RoleName   string    `gorm:"column:role_name;comment:角色名" json:"role_name"`                                // 角色名
	Parent     string    `gorm:"column:parent;comment:上级角色" json:"parent"`                                     // 上级角色
	RoleData   string    `gorm:"column:role_data;comment:权限数据" json:"role_data"`                               // 权限数据
	State      int32     `gorm:"column:state;default:1;comment:状态 1开启,2关闭" json:"state"`                       // 状态 1开启,2关闭
	Memo       string    `gorm:"column:memo;comment:备注" json:"memo"`                                           // 备注
	CreateTime time.Time `gorm:"column:create_time;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"` // 创建时间
}

// TableName XAdminRole's table name
func (*XAdminRole) TableName() string {
	return TableNameXAdminRole
}
