// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameXChat = "x_chat"

// XChat mapped from table <x_chat>
type XChat struct {
	ID         int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	SellerID   int32     `gorm:"column:seller_id" json:"seller_id"`
	Account    string    `gorm:"column:account;comment:会员账号" json:"account"` // 会员账号
	RoomID     int32     `gorm:"column:room_id;comment:房价id" json:"room_id"` // 房价id
	Content    string    `gorm:"column:content;comment:内容" json:"content"`   // 内容
	IP         string    `gorm:"column:ip;comment:ip" json:"ip"`             // ip
	IPLocation string    `gorm:"column:ip_location" json:"ip_location"`
	State      int32     `gorm:"column:state;comment:状态 1待审核,2审核通过,3审核拒绝" json:"state"` // 状态 1待审核,2审核通过,3审核拒绝
	CreateTime time.Time `gorm:"column:create_time;comment:创建时间" json:"create_time"`    // 创建时间
}

// TableName XChat's table name
func (*XChat) TableName() string {
	return TableNameXChat
}
