// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameXChatBanIP = "x_chat_ban_ip"

// XChatBanIP mapped from table <x_chat_ban_ip>
type XChatBanIP struct {
	ID           int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	SellerID     int32     `gorm:"column:seller_id" json:"seller_id"`
	IP           string    `gorm:"column:ip;not null" json:"ip"`
	AdminAccount string    `gorm:"column:admin_account" json:"admin_account"`
	CreateTime   time.Time `gorm:"column:create_time;default:CURRENT_TIMESTAMP" json:"create_time"`
}

// TableName XChatBanIP's table name
func (*XChatBanIP) TableName() string {
	return TableNameXChatBanIP
}
