// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameXHongbaoex = "x_hongbaoex"

// XHongbaoex mapped from table <x_hongbaoex>
type XHongbaoex struct {
	ID         int32     `gorm:"column:id;primaryKey" json:"id"`
	SellerID   int32     `gorm:"column:seller_id" json:"seller_id"`
	HongbaoID  int32     `gorm:"column:hongbao_id" json:"hongbao_id"`
	Account    string    `gorm:"column:account" json:"account"`
	Amount     float64   `gorm:"column:amount" json:"amount"`
	CreateTime time.Time `gorm:"column:create_time" json:"create_time"`
}

// TableName XHongbaoex's table name
func (*XHongbaoex) TableName() string {
	return TableNameXHongbaoex
}
