// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameXHongbao = "x_hongbao"

// XHongbao mapped from table <x_hongbao>
type XHongbao struct {
	ID          int32     `gorm:"column:id;primaryKey;autoIncrement:true;comment:id" json:"id"`                   // id
	SellerID    int32     `gorm:"column:seller_id;comment:运营商" json:"seller_id"`                                  // 运营商
	RoomID      int32     `gorm:"column:room_id;comment:房间Id" json:"room_id"`                                     // 房间Id
	TotalAmount float64   `gorm:"column:total_amount;comment:红包总金额" json:"total_amount"`                          // 红包总金额
	TotalCount  int32     `gorm:"column:total_count;comment:红包个数" json:"total_count"`                             // 红包个数
	UsedAmount  float64   `gorm:"column:used_amount;default:0.000000;comment:已领取金额" json:"used_amount"`           // 已领取金额
	UsedCount   int32     `gorm:"column:used_count;comment:已领取个数" json:"used_count"`                              // 已领取个数
	Sender      string    `gorm:"column:sender;comment:发送者" json:"sender"`                                        // 发送者
	Memo        string    `gorm:"column:memo;comment:备注" json:"memo"`                                             // 备注
	CreateTime  time.Time `gorm:"column:create_time;default:CURRENT_TIMESTAMP;comment:红包发送时间" json:"create_time"` // 红包发送时间
}

// TableName XHongbao's table name
func (*XHongbao) TableName() string {
	return TableNameXHongbao
}
