// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameXKv = "x_kv"

// XKv mapped from table <x_kv>
type XKv struct {
	K string `gorm:"column:k" json:"k"`
	V string `gorm:"column:v" json:"v"`
}

// TableName XKv's table name
func (*XKv) TableName() string {
	return TableNameXKv
}
