// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameXSeller = "x_seller"

// XSeller mapped from table <x_seller>
type XSeller struct {
	ID         int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:自增Id" json:"id"`               // 自增Id
	SellerID   int32     `gorm:"column:seller_id;comment:运营商" json:"seller_id"`                                // 运营商
	State      int32     `gorm:"column:state;default:1;comment:状态 1开启,2关闭" json:"state"`                       // 状态 1开启,2关闭
	SellerName string    `gorm:"column:seller_name;comment:运营商名称" json:"seller_name"`                          // 运营商名称
	Memo       string    `gorm:"column:memo;comment:备注" json:"memo"`                                           // 备注
	CreateTime time.Time `gorm:"column:create_time;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"` // 创建时间
}

// TableName XSeller's table name
func (*XSeller) TableName() string {
	return TableNameXSeller
}
