// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameXStatistic = "x_statistic"

// XStatistic mapped from table <x_statistic>
type XStatistic struct {
	ID         int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	SellerID   int32     `gorm:"column:seller_id" json:"seller_id"`
	RecordType string    `gorm:"column:record_type" json:"record_type"`
	CreateTime time.Time `gorm:"column:create_time" json:"create_time"`
	V1         int32     `gorm:"column:v1" json:"v1"`
	V2         int32     `gorm:"column:v2" json:"v2"`
}

// TableName XStatistic's table name
func (*XStatistic) TableName() string {
	return TableNameXStatistic
}
