// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameXTest = "x_test"

// XTest mapped from table <x_test>
type XTest struct {
	A string `gorm:"column:a" json:"a"`
	B string `gorm:"column:b" json:"b"`
	C string `gorm:"column:c" json:"c"`
}

// TableName XTest's table name
func (*XTest) TableName() string {
	return TableNameXTest
}
